version: "3.2"

services:

  redis:
    image: redis

  api: 
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
      - model

  model:
    build: 
      context: ./model
      dockerfile: Dockerfile
    depends_on:
      - redis